In [1]:
import sys
#!{sys.executable} -m pip install numpy
#!{sys.executable} -m pip install matplotlib

In [2]:
import numpy as np
import matplotlib as pl

In [21]:
def autoc(signal):
    centered_signal = signal - np.mean(signal)
    ft_signal = np.fft.fft(centered_signal)
    powerSpectralDensity = np.abs(ft_signal)**2
    autocovariance = np.fft.ifft(powerSpectralDensity) / len(centered_signal)
    #realautocov = np.real(autocovariance)
    variance = autocovariance.flat[0]
    return np.real(autocovariance / variance)

In [22]:
autoc([1, 0, 1, 0, 1, 0, 1, 0])

array([ 1., -1.,  1., -1.,  1., -1.,  1., -1.])

In [5]:
import json

In [48]:
test_data_file = open('./test-data.json')

In [49]:
data = json.load(test_data_file)

In [50]:
big_signal = data['validSignal']

In [51]:
big_signal[255]

0.136071

In [52]:
big_correlation = autoc(big_signal)

In [53]:
np_big_correlation = np.correlate(big_signal, big_signal, mode='same')[len(big_signal)-1:]

In [54]:
len(np_big_correlation)

1

In [55]:
np_big_correlation[0]

1.1048817953217742

In [56]:
small_signal = [1, 0, 1, 0, 1, 0, 1, 0]

In [57]:
np.correlate(small_signal, small_signal, mode='same')

array([2, 0, 3, 0, 4, 0, 3, 0])

In [58]:
# https://stackoverflow.com/a/40154897/87798
def alt_autoc(x):
    xp = x-np.mean(x)
    f = np.fft.fft(xp)
    p = np.array([np.real(v)**2+np.imag(v)**2 for v in f])
    pi = np.fft.ifft(p)
    #size = int(np.round(x.size/2))
    size = int(np.round(x.size))
    #print(size)
    return np.real(pi)[:size]/np.sum(xp**2)

In [59]:
np.array(small_signal).size

8

In [60]:
alt_autoc(np.array(small_signal))

array([ 1., -1.,  1., -1.,  1., -1.,  1., -1.])

In [61]:
alt_autoc(np.array(big_signal))

array([ 1.        ,  0.97599185,  0.93780087,  0.90767927,  0.89596312,
        0.8913695 ,  0.87379848,  0.83555665,  0.78930881,  0.75562793,
        0.74263316,  0.73761503,  0.71968143,  0.68099481,  0.63412337,
        0.59819015,  0.57936027,  0.56521667,  0.53747092,  0.49069106,
        0.43864704,  0.40086466,  0.38312743,  0.37258403,  0.35145708,
        0.31479104,  0.27532823,  0.25049648,  0.24399107,  0.24172214,
        0.22658609,  0.19546339,  0.16141013,  0.1405045 ,  0.13625694,
        0.13633965,  0.12543664,  0.1010607 ,  0.07559998,  0.06340617,
        0.06664756,  0.07305735,  0.06756887,  0.04715894,  0.02359041,
        0.01077806,  0.01076245,  0.01262203,  0.00371852, -0.01795687,
       -0.04134702, -0.05288128, -0.05027186, -0.04465   , -0.04879086,
       -0.06471415, -0.08286176, -0.09221853, -0.09133733, -0.08990878,
       -0.09901226, -0.11982972, -0.14266971, -0.15672174, -0.1599721 ,
       -0.16012054, -0.16652773, -0.18083347, -0.19528876, -0.20