In [9]:
import sys
#!{sys.executable} -m pip install numpy
#!{sys.executable} -m pip install matplotlib

     |████████████████████████████████| 11.6 MB 2.4 MB/s eta 0:00:01
     |████████████████████████████████| 1.2 MB 13.5 MB/s eta 0:00:01
     |████████████████████████████████| 2.2 MB 9.5 MB/s eta 0:00:01


In [10]:
import numpy as np
import matplotlib as pl

In [14]:
signal = [1, 0, 1, 0, 1, 0, 1, 0]

In [16]:
centered_signal = signal - np.mean(signal)

In [17]:
centered_signal

array([ 0.5, -0.5,  0.5, -0.5,  0.5, -0.5,  0.5, -0.5])

In [19]:
ft_signal = np.fft.fft(centered_signal)
ft_signal

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 4.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

In [20]:
np.abs(ft_signal)

array([0., 0., 0., 0., 4., 0., 0., 0.])

In [22]:
powerSpectralDensity = np.abs(ft_signal)**2
powerSpectralDensity

array([ 0.,  0.,  0.,  0., 16.,  0.,  0.,  0.])

In [25]:
np.fft.ifft(powerSpectralDensity)

array([ 2.+0.j, -2.+0.j,  2.+0.j, -2.+0.j,  2.+0.j, -2.+0.j,  2.+0.j,
       -2.+0.j])

In [26]:
np.fft.ifft(powerSpectralDensity)/len(centered_signal)

array([ 0.25+0.j, -0.25+0.j,  0.25+0.j, -0.25+0.j,  0.25+0.j, -0.25+0.j,
        0.25+0.j, -0.25+0.j])

In [29]:
np.array([ 0.25+12.j, -0.25+0.j,  0.25+0.j, -0.25+0.j,  0.25+0.j, -0.25+0.j,
        0.25+0.j, -0.25+0.j])/8

array([ 0.03125+1.5j, -0.03125+0.j ,  0.03125+0.j , -0.03125+0.j ,
        0.03125+0.j , -0.03125+0.j ,  0.03125+0.j , -0.03125+0.j ])

In [30]:
np.abs([1+3j, -3-4j])

array([3.16227766, 5.        ])

In [31]:
autocovariance = np.fft.ifft(powerSpectralDensity) / len(centered_signal)
autocovariance

array([ 0.25+0.j, -0.25+0.j,  0.25+0.j, -0.25+0.j,  0.25+0.j, -0.25+0.j,
        0.25+0.j, -0.25+0.j])

In [32]:
realautocov = np.real(autocovariance)
realautocov

array([ 0.25, -0.25,  0.25, -0.25,  0.25, -0.25,  0.25, -0.25])

In [34]:
variance = autocovariance.flat[0]
variance

(0.25+0j)

In [35]:
autocovariance.flat

In [36]:
autocovariance / variance

array([ 1.+0.j, -1.+0.j,  1.+0.j, -1.+0.j,  1.+0.j, -1.+0.j,  1.+0.j,
       -1.+0.j])